/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Business;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.OrganizationVolunteer.OrganizationVolunteer;
import Business.Volunteer.Volunteer;
import java.awt.CardLayout;
import java.util.HashSet;
import java.util.Set;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anusha
 */
public class OrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganisationJPanel
     */

    Business business;
    private JPanel homeJPanel;
    
    public OrganizationJPanel(JPanel homeJPanel, Business business) {
        initComponents();
        this.business = business;
        this.homeJPanel = homeJPanel;
        populateOrgEmployeesTbl();
        populateEmployeeRoleCombos();
        populateEnterpriseTypeCombo();
        populateNextEmployeeId();
        populateVolunteerTbl();
        populateAllEmployees();
        populateAllVolunteers();
        populateOrgDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        headinglbl = new javax.swing.JLabel();
        cclogo = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        idlbl = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        citytxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        statetxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        countrytxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        updatedetailsbtn = new javax.swing.JButton();
        prevpasslbl = new javax.swing.JLabel();
        prevpasstxt = new javax.swing.JPasswordField();
        newpasslbl = new javax.swing.JLabel();
        newpasstxt = new javax.swing.JPasswordField();
        confirmpasslbl = new javax.swing.JLabel();
        confirmpasstxt = new javax.swing.JPasswordField();
        updatepassbtn2 = new javax.swing.JButton();
        updatepasswordlbl = new javax.swing.JLabel();
        updatepasswordlbl1 = new javax.swing.JLabel();
        enterprisetypecombo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        needvoltxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        idlbl1 = new javax.swing.JLabel();
        addempid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addempnametxt = new javax.swing.JTextField();
        newpasslbl1 = new javax.swing.JLabel();
        addemppasspwd = new javax.swing.JPasswordField();
        confirmpasslbl1 = new javax.swing.JLabel();
        addempconfirmpwd = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        addemprolecombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        addempcontacttxt = new javax.swing.JTextField();
        addemployeebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateEmpTbl = new javax.swing.JTable();
        updatedetailsbtn2 = new javax.swing.JButton();
        idlbl2 = new javax.swing.JLabel();
        updateEmpIdtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        updateEmpnametxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        updateempcombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        updateEmpContacttxt = new javax.swing.JTextField();
        updateEmpDetailsBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        volunteerTbl = new javax.swing.JTable();
        sendreqBtn = new javax.swing.JButton();
        revokereqBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        EmpjComboBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        assignemptable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        AssignVolunteer = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1597, 979));
        setPreferredSize(new java.awt.Dimension(1597, 979));

        jSplitPane1.setDividerLocation(130);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        headinglbl.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        headinglbl.setForeground(new java.awt.Color(0, 0, 153));
        headinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headinglbl.setText("Organization");

        cclogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Logo.png"))); // NOI18N

        logoutBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 0, 153));
        logoutBtn.setText("LOGOUT");
        logoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cclogo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cclogo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(headinglbl)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel2);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 153));
        jTabbedPane2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(1597, 979));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Welcome to WE VOLUNTEER'S Organization Panel");

        jLabel16.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("<html>As an Organization, you have the power to make a meaningful impact. Using the panel, you can manage your <br>credentials and request volunteers for your initiatives. Streamline your volunteer management with our intuitive system.<br> Raise requests during disaster management or for ongoing projects. WEVolunteer is your central hub for efficient <br>collaboration and community support.</html>\n");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/org home.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(551, 551, 551)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(290, 290, 290))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Home", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        idlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        idlbl.setForeground(new java.awt.Color(0, 0, 153));
        idlbl.setText("ID:");

        idtxt.setEditable(false);
        idtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Name");

        nametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Address");

        addtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        addtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("City");

        citytxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("State");

        statetxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Country");

        countrytxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Enterprise Type");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        updatedetailsbtn.setBackground(new java.awt.Color(0, 0, 153));
        updatedetailsbtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatedetailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatedetailsbtn.setText("UPDATE DETAILS");
        updatedetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedetailsbtnActionPerformed(evt);
            }
        });

        prevpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        prevpasslbl.setForeground(new java.awt.Color(0, 0, 153));
        prevpasslbl.setText("Previous Password:");

        prevpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        newpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        newpasslbl.setForeground(new java.awt.Color(0, 0, 153));
        newpasslbl.setText("New Password:");

        newpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        confirmpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        confirmpasslbl.setForeground(new java.awt.Color(0, 0, 153));
        confirmpasslbl.setText("Confirm Password:");

        confirmpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        updatepassbtn2.setBackground(new java.awt.Color(0, 0, 153));
        updatepassbtn2.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatepassbtn2.setForeground(new java.awt.Color(255, 255, 255));
        updatepassbtn2.setText("UPDATE PASSWORD");
        updatepassbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepassbtn2ActionPerformed(evt);
            }
        });

        updatepasswordlbl.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        updatepasswordlbl.setForeground(new java.awt.Color(0, 0, 153));
        updatepasswordlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatepasswordlbl.setText("Update Basic Details");

        updatepasswordlbl1.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        updatepasswordlbl1.setForeground(new java.awt.Color(0, 0, 153));
        updatepasswordlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatepasswordlbl1.setText("Update Password");

        enterprisetypecombo.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        enterprisetypecombo.setForeground(new java.awt.Color(0, 0, 153));
        enterprisetypecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterprisetypecomboActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Need Volunteer Count");

        needvoltxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(updatepasswordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(92, 92, 92)
                                .addComponent(needvoltxt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(updatedetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addComponent(idtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nametxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statetxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countrytxt)
                                    .addComponent(enterprisetypecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(citytxt))))
                        .addGap(187, 187, 187)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prevpasslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newpasslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmpasslbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatepassbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prevpasstxt)
                                .addComponent(newpasstxt)
                                .addComponent(confirmpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(updatepasswordlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(244, 244, 244))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(updatepasswordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(addtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(statetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(countrytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(enterprisetypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(needvoltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(updatepasswordlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(prevpasstxt))
                                    .addComponent(prevpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(confirmpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addComponent(updatepassbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(13, 13, 13)
                .addComponent(updatedetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Manage Organization", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        idlbl1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        idlbl1.setForeground(new java.awt.Color(0, 0, 153));
        idlbl1.setText("ID:");

        addempid.setEditable(false);
        addempid.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Name:");

        addempnametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        newpasslbl1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        newpasslbl1.setForeground(new java.awt.Color(0, 0, 153));
        newpasslbl1.setText("New Password:");

        addemppasspwd.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        confirmpasslbl1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        confirmpasslbl1.setForeground(new java.awt.Color(0, 0, 153));
        confirmpasslbl1.setText("Confirm Password:");

        addempconfirmpwd.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Role:");

        jLabel11.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Contact:");

        addempcontacttxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        addemployeebtn.setBackground(new java.awt.Color(0, 0, 153));
        addemployeebtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        addemployeebtn.setForeground(new java.awt.Color(255, 255, 255));
        addemployeebtn.setText("ADD EMPLOYEE");
        addemployeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemployeebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(newpasslbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmpasslbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(addempconfirmpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(881, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addemprolecombo, 0, 217, Short.MAX_VALUE)
                                    .addComponent(addemppasspwd, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(addemployeebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addempcontacttxt))
                                .addGap(0, 881, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idlbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addempid)
                            .addComponent(addempnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addempid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addempnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpasslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addemppasspwd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmpasslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addempconfirmpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(addemprolecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(addempcontacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(addemployeebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Employee", jPanel6);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        updateEmpTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee Id", "Name", "Role", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(updateEmpTbl);
        if (updateEmpTbl.getColumnModel().getColumnCount() > 0) {
            updateEmpTbl.getColumnModel().getColumn(0).setResizable(false);
            updateEmpTbl.getColumnModel().getColumn(1).setResizable(false);
            updateEmpTbl.getColumnModel().getColumn(2).setResizable(false);
            updateEmpTbl.getColumnModel().getColumn(3).setResizable(false);
        }

        updatedetailsbtn2.setBackground(new java.awt.Color(0, 0, 153));
        updatedetailsbtn2.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatedetailsbtn2.setForeground(new java.awt.Color(255, 255, 255));
        updatedetailsbtn2.setText("UPDATE EMPLOYEE DETAILS");
        updatedetailsbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedetailsbtn2ActionPerformed(evt);
            }
        });

        idlbl2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        idlbl2.setForeground(new java.awt.Color(0, 0, 153));
        idlbl2.setText("ID:");

        updateEmpIdtxt.setEditable(false);
        updateEmpIdtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Name:");

        updateEmpnametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Role:");

        jLabel13.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Contact:");

        updateEmpContacttxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        updateEmpDetailsBtn.setBackground(new java.awt.Color(0, 0, 153));
        updateEmpDetailsBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updateEmpDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateEmpDetailsBtn.setText("SAVE");
        updateEmpDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmpDetailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idlbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateEmpIdtxt)
                            .addComponent(updateEmpnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateEmpContacttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(updateempcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(updateEmpDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatedetailsbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(610, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(updateempcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(updateEmpContacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateEmpDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(updatedetailsbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateEmpIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(updateEmpnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(427, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Update Employees", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        volunteerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Volunteer Id", "Name", "Contact", "City", "Age", "Gender", "Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(volunteerTbl);
        if (volunteerTbl.getColumnModel().getColumnCount() > 0) {
            volunteerTbl.getColumnModel().getColumn(0).setResizable(false);
            volunteerTbl.getColumnModel().getColumn(1).setResizable(false);
            volunteerTbl.getColumnModel().getColumn(1).setPreferredWidth(200);
            volunteerTbl.getColumnModel().getColumn(2).setResizable(false);
            volunteerTbl.getColumnModel().getColumn(3).setResizable(false);
            volunteerTbl.getColumnModel().getColumn(4).setResizable(false);
            volunteerTbl.getColumnModel().getColumn(5).setResizable(false);
            volunteerTbl.getColumnModel().getColumn(6).setResizable(false);
        }

        sendreqBtn.setBackground(new java.awt.Color(0, 0, 153));
        sendreqBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        sendreqBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendreqBtn.setText("Send Request");
        sendreqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendreqBtnActionPerformed(evt);
            }
        });

        revokereqBtn.setBackground(new java.awt.Color(0, 0, 153));
        revokereqBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        revokereqBtn.setForeground(new java.awt.Color(255, 255, 255));
        revokereqBtn.setText("Revoke Request");
        revokereqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revokereqBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(665, 665, 665)
                        .addComponent(sendreqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(revokereqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(570, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendreqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revokereqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(534, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Connect to Volunteers", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Select Employees: ");

        assignemptable.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        assignemptable.setForeground(new java.awt.Color(0, 0, 153));
        assignemptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Age", "Gender", "City", "State", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(assignemptable);
        if (assignemptable.getColumnModel().getColumnCount() > 0) {
            assignemptable.getColumnModel().getColumn(0).setResizable(false);
            assignemptable.getColumnModel().getColumn(1).setResizable(false);
            assignemptable.getColumnModel().getColumn(2).setResizable(false);
            assignemptable.getColumnModel().getColumn(3).setResizable(false);
            assignemptable.getColumnModel().getColumn(4).setResizable(false);
            assignemptable.getColumnModel().getColumn(5).setResizable(false);
            assignemptable.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel18.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Select Volunteer from Below list to assign to Employee");

        AssignVolunteer.setBackground(new java.awt.Color(0, 0, 153));
        AssignVolunteer.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        AssignVolunteer.setForeground(new java.awt.Color(255, 255, 255));
        AssignVolunteer.setText("Assign Volunteer");
        AssignVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignVolunteerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AssignVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(42, 42, 42)
                            .addComponent(EmpjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(EmpjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jLabel18)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(AssignVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Assign Employee", jPanel7);

        jSplitPane1.setRightComponent(jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatedetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedetailsbtnActionPerformed
        Boolean flag = true;
        int orgId = Integer.parseInt(idtxt.getText());
        
        String name = nametxt.getText();
        if(name.matches("[a-zA-Z ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Name");
            flag = false;
            nametxt.setText("");
        }
        String address = addtxt.getText();
        
        String city = citytxt.getText();
        if(city.matches("[a-zA-Z, ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect City");
            flag = false;
            citytxt.setText("");
        }
        
        String state = statetxt.getText();
        if(state.matches("[a-zA-Z, ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect State");
            flag = false;
            statetxt.setText("");
        }
        
        String country = countrytxt.getText();
        if(state.matches("[a-zA-Z, ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Country");
            flag = false;
            countrytxt.setText("");
        }
        
        String entType = enterprisetypecombo.getSelectedItem().toString();
        
        int needvolcount = Integer.parseInt(needvoltxt.getText());
        
        Organization org = business.getOrganizationdirectory().findOrg(orgId);
        
        if(flag==true){
            org.setName(name);
            org.setAddress(address);
            org.setCity(city);
            org.setState(state);
            org.setCountry(country);
            org.setNeedVolunteerCount(needvolcount);
            
            // Finding type of Enterprise for organization
            for(Enterprise e: business.getEnterprisedirectory().getAllEnter()){
                Organization orgfound = e.findOrg(orgId);
                if(orgfound!=null){
                   e.getOrglist().remove(orgfound);
                }
            }
            
            Enterprise newenterprise = business.getEnterprisedirectory().findEnterprise(entType);
            newenterprise.addOrg(org);
                        
            JOptionPane.showMessageDialog(null, "Organization details updated successfully!");     
        }
        else{
            JOptionPane.showMessageDialog(null, "Error while updating Organization details. Check the information before submitting!");
        }
    }//GEN-LAST:event_updatedetailsbtnActionPerformed

    private void updatepassbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepassbtn2ActionPerformed
        Boolean flag = true;
        int orgId = Integer.parseInt(idtxt.getText());
        String prevPassword =String.valueOf(prevpasstxt.getPassword());
        String password = String.valueOf(newpasstxt.getPassword());
        String confirmpassword = String.valueOf(confirmpasstxt.getPassword());
        
        if(prevPassword.equals(password)){
            JOptionPane.showMessageDialog(null, "Previous password and new password cannot be same!");
            newpasstxt.setText("");
            confirmpasstxt.setText("");
            flag = false;
        }
        if(password.matches("[a-zA-Z0-9@._-]{3,}") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Password Format");
            newpasstxt.setText("");
            confirmpasstxt.setText("");
            flag = false;
        }
        
        if(!password.equals(confirmpassword)){
            JOptionPane.showMessageDialog(null, "Confirm password doesnot match with set Password");
            confirmpasstxt.setText("");
            flag = false;
        }
        
        Organization org = business.getOrganizationdirectory().findOrg(orgId);
        String orgPass = String.valueOf(org.getOrganizationPass());
        Boolean checkExistingPassStatus = false;
        
        char[] hashedprevpassword = business.hashPassword(prevPassword);
        
        if(orgPass.equals(String.valueOf(hashedprevpassword))){
            checkExistingPassStatus=true;
        }
        
        if(checkExistingPassStatus==false){
            JOptionPane.showMessageDialog(null, "Incorrect Previous Password!");
            prevpasstxt.setText("");
            flag = false;
        }
//        System.out.println(prevPassword +"--"+password+"--"+confirmpassword);
        if(flag == true){
            org.setOrganizationPass(business.hashPassword(password));
            JOptionPane.showMessageDialog(null, "Password updated Successfully");         
        }
        else{
            JOptionPane.showMessageDialog(null, "Re-enter correct details to update password.");
        }
        
        
    }//GEN-LAST:event_updatepassbtn2ActionPerformed

    private void addemployeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemployeebtnActionPerformed
        Organization org = business.getOrganization();
        int personid = Integer.parseInt(addempid.getText());
        String name = addempnametxt.getText();
        char[] password = addemppasspwd.getPassword();
        String phone = addempcontacttxt.getText();
        String role = addemprolecombo.getSelectedItem().toString();
        char[] hashedpassword = business.hashPassword(password);
        
        Employee e = business.getEmployeedirectory().newEmployee(personid, name, hashedpassword, "Employee", phone, role);
        org.addEmployee(e);
                
        JOptionPane.showMessageDialog(null, "Employee added Successfully"); 
        populateOrgEmployeesTbl();
        populateNextEmployeeId();
        addempnametxt.setText("");
        addemppasspwd.setText("");
        addempconfirmpwd.setText("");
        addempcontacttxt.setText("");
    }//GEN-LAST:event_addemployeebtnActionPerformed

    private void updatedetailsbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedetailsbtn2ActionPerformed
        int selectedRowIndex = updateEmpTbl.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) updateEmpTbl.getModel();
            updateEmpIdtxt.setText(String.valueOf(model.getValueAt(selectedRowIndex, 0)));
            updateEmpnametxt.setText(String.valueOf(model.getValueAt(selectedRowIndex, 1)));
            updateempcombo.setSelectedItem(String.valueOf(model.getValueAt(selectedRowIndex, 2)));
            updateEmpContacttxt.setText(String.valueOf(model.getValueAt(selectedRowIndex, 3)));
                        
        }
    }//GEN-LAST:event_updatedetailsbtn2ActionPerformed

    private void updateEmpDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmpDetailsBtnActionPerformed
        int empid = Integer.parseInt(updateEmpIdtxt.getText());
        Employee e = business.getEmployeedirectory().findEmployee(empid);
        e.setName(updateEmpnametxt.getText());
        e.setRole(updateempcombo.getSelectedItem().toString());
        e.setPhone(updateEmpContacttxt.getText());
        populateOrgEmployeesTbl();
    }//GEN-LAST:event_updateEmpDetailsBtnActionPerformed

    private void addtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtxtActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        homeJPanel.remove(this);
        CardLayout layout = (CardLayout) homeJPanel.getLayout();
        layout.previous(homeJPanel);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void enterprisetypecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterprisetypecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterprisetypecomboActionPerformed

    private void sendreqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendreqBtnActionPerformed
        Organization org = business.getOrganization();
        int selectedRowIndex = volunteerTbl.getSelectedRow();
        int vid = 101;
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a volunteer to request.");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) volunteerTbl.getModel();
            vid = Integer.parseInt(String.valueOf(model.getValueAt(selectedRowIndex, 0)));
        }
        
        Volunteer v = business.getVolunteerdirectory().findVolunteer(vid);
        // Check if request already there
        OrganizationVolunteer ovExist = business.getOrganizationvolunteerdirectory().findRequestIfPresent(org, v);
        //Send request if not alreadyexists
        if(ovExist==null){
            OrganizationVolunteer ov = business.getOrganizationvolunteerdirectory().addRequest(org, v, "Pending");
            JOptionPane.showMessageDialog(null, "Request sent to volunteer successfully");
            populateVolunteerTbl();
        }
        else{
            JOptionPane.showMessageDialog(null, "Request cannot be sent to this volunteer. Request might be pending/accepted/rejected.");
        }
    }//GEN-LAST:event_sendreqBtnActionPerformed

    private void revokereqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revokereqBtnActionPerformed
        Organization org = business.getOrganization();
        int selectedRowIndex = volunteerTbl.getSelectedRow();
        int vid = 101;
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a volunteer to request.");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) volunteerTbl.getModel();
            vid = Integer.parseInt(String.valueOf(model.getValueAt(selectedRowIndex, 0)));
        }
        
        Volunteer v = business.getVolunteerdirectory().findVolunteer(vid);
        ArrayList<OrganizationVolunteer> ovlist = business.getOrganizationvolunteerdirectory().removeRequest(org, v);
        JOptionPane.showMessageDialog(null, "Request revoked successfully");
        
        populateVolunteerTbl();
    }//GEN-LAST:event_revokereqBtnActionPerformed

    private void AssignVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignVolunteerActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = assignemptable.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) assignemptable.getModel();
            int vid = Integer.parseInt(String.valueOf(model.getValueAt(selectedRowIndex, 0)));  
            
            //Getting employee and volunteer to assign
            Employee e = business.getEmployeedirectory().findEmployeeByName(EmpjComboBox.getSelectedItem().toString());
            Volunteer v = business.getVolunteerdirectory().findVolunteer(vid);
            e.addVolToEmplist(v);
            //System.out.println(e.getVolToEmplist());
            JOptionPane.showMessageDialog(null, "Volunteer assigned to employee successfully");
            ((DefaultTableModel) assignemptable.getModel()).removeRow(selectedRowIndex);
            
        }
    }//GEN-LAST:event_AssignVolunteerActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignVolunteer;
    private javax.swing.JComboBox<String> EmpjComboBox;
    private javax.swing.JPasswordField addempconfirmpwd;
    private javax.swing.JTextField addempcontacttxt;
    private javax.swing.JTextField addempid;
    private javax.swing.JButton addemployeebtn;
    private javax.swing.JTextField addempnametxt;
    private javax.swing.JPasswordField addemppasspwd;
    private javax.swing.JComboBox<String> addemprolecombo;
    private javax.swing.JTextField addtxt;
    private javax.swing.JTable assignemptable;
    private javax.swing.JLabel cclogo;
    private javax.swing.JTextField citytxt;
    private javax.swing.JLabel confirmpasslbl;
    private javax.swing.JLabel confirmpasslbl1;
    private javax.swing.JPasswordField confirmpasstxt;
    private javax.swing.JTextField countrytxt;
    private javax.swing.JComboBox<String> enterprisetypecombo;
    private javax.swing.JLabel headinglbl;
    private javax.swing.JLabel idlbl;
    private javax.swing.JLabel idlbl1;
    private javax.swing.JLabel idlbl2;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField needvoltxt;
    private javax.swing.JLabel newpasslbl;
    private javax.swing.JLabel newpasslbl1;
    private javax.swing.JPasswordField newpasstxt;
    private javax.swing.JLabel prevpasslbl;
    private javax.swing.JPasswordField prevpasstxt;
    private javax.swing.JButton revokereqBtn;
    private javax.swing.JButton sendreqBtn;
    private javax.swing.JTextField statetxt;
    private javax.swing.JTextField updateEmpContacttxt;
    private javax.swing.JButton updateEmpDetailsBtn;
    private javax.swing.JTextField updateEmpIdtxt;
    private javax.swing.JTable updateEmpTbl;
    private javax.swing.JTextField updateEmpnametxt;
    private javax.swing.JButton updatedetailsbtn;
    private javax.swing.JButton updatedetailsbtn2;
    private javax.swing.JComboBox<String> updateempcombo;
    private javax.swing.JButton updatepassbtn2;
    private javax.swing.JLabel updatepasswordlbl;
    private javax.swing.JLabel updatepasswordlbl1;
    private javax.swing.JTable volunteerTbl;
    // End of variables declaration//GEN-END:variables

    private void populateOrgDetails() {
        Organization org = business.getOrganization();
        int id = org.getId();
        String name = org.getName();
        String address = org.getAddress();
        String city = org.getCity();
        String state = org.getState();
        String country = org.getCountry();
        String type="";
//        Finding type of Enterprise type for organization
        for(Enterprise e: business.getEnterprisedirectory().getAllEnter()){
            Organization orgfound = e.findOrg(id);
            if(orgfound!=null){
                type = e.getType();
            }
        }
        
        int needVolCount = org.getNeedVolunteerCount();
        
        idtxt.setText(String.valueOf(id));
        nametxt.setText(name);
        addtxt.setText(address);
        citytxt.setText(city);
        statetxt.setText(state);
        countrytxt.setText(country);
        enterprisetypecombo.setSelectedItem(type);
        needvoltxt.setText(String.valueOf(needVolCount));
    }

    private void populateEmployeeRoleCombos() {
        Set<String> empRoleSet = new HashSet<String>();
        for(Employee emp : business.getEmployeedirectory().getAllEmp()){
            empRoleSet.add(emp.getRole());
        }
        for(String emprole : empRoleSet) {
            addemprolecombo.addItem(emprole);
            updateempcombo.addItem(emprole);
        }
        
    }

    private void populateNextEmployeeId() {
        ArrayList<Employee> emplist = business.getEmployeedirectory().getAllEmp();
        Employee lastemployee = emplist.get(emplist.size() - 1);
        int nextid = lastemployee.getPersonid() + 1;
        addempid.setText(String.valueOf(nextid));
    }

    private void populateOrgEmployeesTbl() {
        Organization org = business.getOrganization();
        headinglbl.setText(org.getName());
        
//        Table populate
        DefaultTableModel dtm = (DefaultTableModel) updateEmpTbl.getModel();
        dtm.setRowCount(0);
        for(Employee e: org.getEmpDirectory()){
            Object[] row = new Object[4];
            row[0] = e.getPersonid();
            row[1] = e.getName();
            row[2] = e.getRole();
            row[3] = e.getPhone();
            dtm.addRow(row);      
        }
    }

    private void populateVolunteerTbl() {
        Organization org= business.getOrganization();
        ArrayList<Volunteer> vollist = business.getVolunteerdirectory().getAllVol();    
        ArrayList<Volunteer> selectedvolunteer = new ArrayList<>();
        for(Volunteer v : vollist){
            String volcity = v.getCity();
            String volcountry = v.getCountry();
            if(volcity.equalsIgnoreCase(org.getCity()) && volcountry.equalsIgnoreCase(org.getCountry())){
                selectedvolunteer.add(v);
            }
        }
                
        DefaultTableModel dtm = (DefaultTableModel) volunteerTbl.getModel();
        dtm.setRowCount(0);
        for(Volunteer v : selectedvolunteer){
            Object[] row = new Object[7];
            row[0] = v.getPersonid();
            row[1] = v.getName();
            
            row[3] = v.getCity();
            row[4] = v.getAge();
            row[5] = v.getGender();
            OrganizationVolunteer ov = business.getOrganizationvolunteerdirectory().findRequestIfPresent(org, v);
            if(ov!=null){
                row[6] = ov.getRequeststatus();
//                Showcase volunteer contact only when request is accpted
                if(ov.getRequeststatus().equalsIgnoreCase("Accepted")){
                    row[2] = v.getPhone();
                }
                else{
                    row[2] = "";
                }
            }
            else{
                row[6] = "";
            }
            dtm.addRow(row);      
        }
        
    }

    private void populateAllEmployees() {
        Organization org = business.getOrganization();
        for(Employee e: org.getEmpDirectory()){
            String name = e.getName();
            EmpjComboBox.addItem(name);     
        }          
    }
    
    private void populateAllVolunteers(){
        Organization org= business.getOrganization();
        ArrayList<Volunteer> vollist = business.getVolunteerdirectory().getAllVol();    
        ArrayList<Volunteer> selectedvolunteer = new ArrayList<>();
        for(Volunteer v : vollist){
            String volcity = v.getCity();
            String volcountry = v.getCountry();
            OrganizationVolunteer ov = business.getOrganizationvolunteerdirectory().findRequestIfPresent(org, v);
            if(ov!=null && ov.getRequeststatus().equalsIgnoreCase("Accepted")){
                selectedvolunteer.add(v);
            }
        }
        
        DefaultTableModel dtm = (DefaultTableModel) assignemptable.getModel();
        dtm.setRowCount(0);
        for(Volunteer v : selectedvolunteer){
            Object[] row = new Object[7];
            row[0] = v.getPersonid();
            row[1] = v.getName();
            row[2] = v.getAge();
            row[3] = v.getGender();
            row[4] = v.getCity();
            row[5] = v.getState();
            row[6] = v.getPhone();
            dtm.addRow(row);      
        }
    }
        
    private void populateEnterpriseTypeCombo() {
        Set<String> enterprisetypeset = new HashSet<String>();
        for(Enterprise ent : business.getEnterprisedirectory().getAllEnter()){
            enterprisetypeset.add(ent.getType());
        }
        for(String enttype : enterprisetypeset) {
            enterprisetypecombo.addItem(enttype);
        }
    }

}
