/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.OrganizationVolunteer.OrganizationVolunteer;
import Business.Volunteer.Volunteer;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anusha
 */
public class VolunteerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerJPanel
     */

    private JPanel homeJPanel;
    Business business;
    
    public VolunteerJPanel(JPanel homeJPanel, Business business) {
        initComponents();
        this.homeJPanel = homeJPanel;
        this.business = business;
        populateOrganizationRequests();
        populateVolunteerDetails();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cclogo = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        updatepasswordlbl = new javax.swing.JLabel();
        idlbl = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        Namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        agetxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        genderjComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        citytxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        statetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        countrytxt = new javax.swing.JTextField();
        updatedetailsbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        updatepasswordlbl1 = new javax.swing.JLabel();
        prevpasslbl = new javax.swing.JLabel();
        prevpasstxt = new javax.swing.JPasswordField();
        newpasslbl = new javax.swing.JLabel();
        newpasstxt = new javax.swing.JPasswordField();
        confirmpasslbl = new javax.swing.JLabel();
        confirmpasstxt = new javax.swing.JPasswordField();
        updatepassbtn = new javax.swing.JButton();
        contacttxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orgRequestTable = new javax.swing.JTable();
        acceptreqBtn = new javax.swing.JButton();
        rejectreqBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1597, 943));
        setPreferredSize(new java.awt.Dimension(1597, 943));

        jSplitPane1.setDividerLocation(130);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Volunteer Panel");

        cclogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Logo.png"))); // NOI18N

        logoutBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 0, 153));
        logoutBtn.setText("LOGOUT");
        logoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cclogo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 500, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cclogo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 153));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Welcome to WE VOLUNTEER'S Volunteer Panel");

        jLabel16.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("<html>As a Volunteer, you play a vital role in making a positive impact on communities. <br>Explore a myriad of volunteering opportunities seamlessly mapped to aid requests. <br>Sign up, choose tasks based on your interests, and be part of initiatives that matter. <br>Your contributions help create a stronger, more engaged community. Let's make a difference together!\n<html> ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vol home.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(290, 290, 290))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Home", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatepasswordlbl.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        updatepasswordlbl.setForeground(new java.awt.Color(0, 0, 153));
        updatepasswordlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatepasswordlbl.setText("Update Basic Details");
        jPanel4.add(updatepasswordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 48, 349, 49));

        idlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        idlbl.setForeground(new java.awt.Color(0, 0, 153));
        idlbl.setText("ID:");
        jPanel4.add(idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 108, 29));

        idtxt.setEditable(false);
        idtxt.setEnabled(false);
        jPanel4.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 220, 30));

        Namelbl.setForeground(new java.awt.Color(0, 0, 153));
        Namelbl.setText("Name");
        jPanel4.add(Namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        nametxt.setPreferredSize(new java.awt.Dimension(64, 23));
        jPanel4.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 219, 29));

        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Age");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        agetxt.setPreferredSize(new java.awt.Dimension(64, 23));
        agetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agetxtActionPerformed(evt);
            }
        });
        jPanel4.add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 219, 30));

        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Gender");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        genderjComboBox.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        genderjComboBox.setForeground(new java.awt.Color(0, 0, 153));
        genderjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel4.add(genderjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 220, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Address");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        jPanel4.add(addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 220, 30));

        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("City");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));
        jPanel4.add(citytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 220, 30));

        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("State");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));
        jPanel4.add(statetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 219, 30));

        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Country");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));
        jPanel4.add(countrytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 220, 30));

        updatedetailsbtn.setBackground(new java.awt.Color(0, 0, 153));
        updatedetailsbtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatedetailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatedetailsbtn.setText("UPDATE DETAILS");
        updatedetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedetailsbtnActionPerformed(evt);
            }
        });
        jPanel4.add(updatedetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 162, 31));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 50, 420));

        updatepasswordlbl1.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        updatepasswordlbl1.setForeground(new java.awt.Color(0, 0, 153));
        updatepasswordlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatepasswordlbl1.setText("Update Password");
        jPanel4.add(updatepasswordlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 70, -1, -1));

        prevpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        prevpasslbl.setForeground(new java.awt.Color(0, 0, 153));
        prevpasslbl.setText("Previous Password:");
        jPanel4.add(prevpasslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, -1, -1));

        prevpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jPanel4.add(prevpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 123, 190, 30));

        newpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        newpasslbl.setForeground(new java.awt.Color(0, 0, 153));
        newpasslbl.setText("New Password:");
        jPanel4.add(newpasslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, -1, -1));

        newpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jPanel4.add(newpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 190, 30));

        confirmpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        confirmpasslbl.setForeground(new java.awt.Color(0, 0, 153));
        confirmpasslbl.setText("Confirm Password:");
        jPanel4.add(confirmpasslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, -1, -1));

        confirmpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jPanel4.add(confirmpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, 190, 30));

        updatepassbtn.setBackground(new java.awt.Color(0, 0, 153));
        updatepassbtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatepassbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatepassbtn.setText("UPDATE PASSWORD");
        updatepassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepassbtnActionPerformed(evt);
            }
        });
        jPanel4.add(updatepassbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 180, 40));

        contacttxt.setPreferredSize(new java.awt.Dimension(64, 23));
        contacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttxtActionPerformed(evt);
            }
        });
        jPanel4.add(contacttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 219, 30));

        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Contact");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));

        jTabbedPane2.addTab("Manage Profile", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        orgRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Org  Id", "Organization Name", "Type", "Address", "City", "Need Volunteer Count", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgRequestTable);
        if (orgRequestTable.getColumnModel().getColumnCount() > 0) {
            orgRequestTable.getColumnModel().getColumn(0).setResizable(false);
            orgRequestTable.getColumnModel().getColumn(1).setResizable(false);
            orgRequestTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            orgRequestTable.getColumnModel().getColumn(2).setResizable(false);
            orgRequestTable.getColumnModel().getColumn(2).setPreferredWidth(170);
            orgRequestTable.getColumnModel().getColumn(3).setResizable(false);
            orgRequestTable.getColumnModel().getColumn(3).setPreferredWidth(200);
            orgRequestTable.getColumnModel().getColumn(4).setResizable(false);
            orgRequestTable.getColumnModel().getColumn(5).setResizable(false);
            orgRequestTable.getColumnModel().getColumn(5).setPreferredWidth(200);
            orgRequestTable.getColumnModel().getColumn(6).setResizable(false);
        }

        acceptreqBtn.setBackground(new java.awt.Color(0, 0, 153));
        acceptreqBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        acceptreqBtn.setForeground(new java.awt.Color(255, 255, 255));
        acceptreqBtn.setText("Accept Request");
        acceptreqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptreqBtnActionPerformed(evt);
            }
        });

        rejectreqBtn.setBackground(new java.awt.Color(0, 0, 153));
        rejectreqBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        rejectreqBtn.setForeground(new java.awt.Color(255, 255, 255));
        rejectreqBtn.setText("Reject Request");
        rejectreqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectreqBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(acceptreqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(rejectreqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(315, 315, 315))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptreqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectreqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(380, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Organization Requests", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        homeJPanel.remove(this);
        CardLayout layout = (CardLayout) homeJPanel.getLayout();
        layout.previous(homeJPanel);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void agetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agetxtActionPerformed

    private void updatedetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedetailsbtnActionPerformed
        Boolean flag = true;
        int volId = Integer.parseInt(idtxt.getText());

        String name = nametxt.getText();
        if(name.matches("[a-zA-Z ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Name");
            flag = false;
            nametxt.setText("");
        }
        
        String age = agetxt.getText();
        if(age.matches("[0-9][0-9]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Age");
            flag = false;
            agetxt.setText("");
        }
        int ageint = Integer.parseInt(age);
        
        String address = addresstxt.getText();

        String city = citytxt.getText();
        if(city.matches("[a-zA-Z, ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect City");
            flag = false;
            citytxt.setText("");
        }

        String state = statetxt.getText();
        if(state.matches("[a-zA-Z, ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect State");
            flag = false;
            statetxt.setText("");
        }

        String country = countrytxt.getText();
        if(country.matches("[a-zA-Z, ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Country");
            flag = false;
            countrytxt.setText("");
        }
        
        String contact = contacttxt.getText();
        if(contact.matches("[0-9,+ ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Contact");
            flag = false;
            contacttxt.setText("");
        }

        String gender = genderjComboBox.getSelectedItem().toString();

        Volunteer vol = business.getVolunteerdirectory().findVolunteer(volId);

        if(flag==true){
            vol.setName(name);
            vol.setAge(ageint);
            vol.setGender(gender);
            vol.setAddress(address);
            vol.setCity(city);
            vol.setState(state);
            vol.setCountry(country);
            vol.setPhone(contact);

            JOptionPane.showMessageDialog(null, "Volunteer details updated successfully!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Error while updating Volunteer details. Check the information before submitting!");
        }
    }//GEN-LAST:event_updatedetailsbtnActionPerformed

    private void updatepassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepassbtnActionPerformed
        Boolean flag = true;
        int volId = Integer.parseInt(idtxt.getText());
        String prevPassword =String.valueOf(prevpasstxt.getPassword());
        String password = String.valueOf(newpasstxt.getPassword());
        String confirmpassword = String.valueOf(confirmpasstxt.getPassword());

        if(prevPassword.equals(password)){
            JOptionPane.showMessageDialog(null, "Previous password and new password cannot be same!");
            newpasstxt.setText("");
            confirmpasstxt.setText("");
            flag = false;
        }
        if(password.matches("[a-zA-Z0-9@._-]{3,}") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Password Format");
            newpasstxt.setText("");
            confirmpasstxt.setText("");
            flag = false;
        }

        if(!password.equals(confirmpassword)){
            JOptionPane.showMessageDialog(null, "Confirm password doesnot match with set Password");
            confirmpasstxt.setText("");
            flag = false;
        }

        Volunteer vol = business.getVolunteerdirectory().findVolunteer(volId);
        String volPass = String.valueOf(vol.getPassword());
        Boolean checkExistingPassStatus = false;

        char[] hashedprevpassword = business.hashPassword(prevPassword);
        
        if(volPass.equals(String.valueOf(hashedprevpassword))){
            checkExistingPassStatus=true;
        }

        if(checkExistingPassStatus==false){
            JOptionPane.showMessageDialog(null, "Incorrect Previous Password!");
            prevpasstxt.setText("");
            flag = false;
        }
        //        System.out.println(prevPassword +"--"+password+"--"+confirmpassword);
        if(flag == true){
            vol.setPassword(business.hashPassword(password));
            JOptionPane.showMessageDialog(null, "Password updated Successfully");
        }
        else{
            JOptionPane.showMessageDialog(null, "Re-enter correct details to update password.");
        }

    }//GEN-LAST:event_updatepassbtnActionPerformed

    private void acceptreqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptreqBtnActionPerformed
        int selectedRowIndex = orgRequestTable.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to accept.");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) orgRequestTable.getModel();
            int org_id = Integer.parseInt(String.valueOf(model.getValueAt(selectedRowIndex, 0)));
            int vol_id = business.getVolunteer().getPersonid();
            Boolean update_status = business.getOrganizationvolunteerdirectory().requestUpdate(org_id, vol_id, "Accepted");
            
            if(update_status==true){
                JOptionPane.showMessageDialog(null, "Request accepted successfully.");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error in accepting request. Please try again.");
            }
            populateOrganizationRequests();
        }
    }//GEN-LAST:event_acceptreqBtnActionPerformed

    private void rejectreqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectreqBtnActionPerformed
        int selectedRowIndex = orgRequestTable.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to reject.");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) orgRequestTable.getModel();
            int org_id = Integer.parseInt(String.valueOf(model.getValueAt(selectedRowIndex, 0)));
            int vol_id = business.getVolunteer().getPersonid();
            Boolean update_status = business.getOrganizationvolunteerdirectory().requestUpdate(org_id, vol_id, "Rejected");
            
            if(update_status==true){
                JOptionPane.showMessageDialog(null, "Request rejected successfully.");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error in rejecting request. Please try again.");
            }
            populateOrganizationRequests();
        }
    }//GEN-LAST:event_rejectreqBtnActionPerformed

    private void contacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Namelbl;
    private javax.swing.JButton acceptreqBtn;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JTextField agetxt;
    private javax.swing.JLabel cclogo;
    private javax.swing.JTextField citytxt;
    private javax.swing.JLabel confirmpasslbl;
    private javax.swing.JPasswordField confirmpasstxt;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JTextField countrytxt;
    private javax.swing.JComboBox<String> genderjComboBox;
    private javax.swing.JLabel idlbl;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel newpasslbl;
    private javax.swing.JPasswordField newpasstxt;
    private javax.swing.JTable orgRequestTable;
    private javax.swing.JLabel prevpasslbl;
    private javax.swing.JPasswordField prevpasstxt;
    private javax.swing.JButton rejectreqBtn;
    private javax.swing.JTextField statetxt;
    private javax.swing.JButton updatedetailsbtn;
    private javax.swing.JButton updatepassbtn;
    private javax.swing.JLabel updatepasswordlbl;
    private javax.swing.JLabel updatepasswordlbl1;
    // End of variables declaration//GEN-END:variables


    private void populateOrganizationRequests() {
        int volid = business.getVolunteer().getPersonid();
        
        ArrayList<OrganizationVolunteer> ovlist = business.getOrganizationvolunteerdirectory().getAllRequests();
        ArrayList<OrganizationVolunteer> requestedorgs = new ArrayList<>();
        for(OrganizationVolunteer ov : ovlist){
            int volidreq = ov.getVol().getPersonid();
            
            if(volidreq == volid){
                requestedorgs.add(ov);
            }
        }
        
        DefaultTableModel dtm = (DefaultTableModel) orgRequestTable.getModel();
        dtm.setRowCount(0);
        for(OrganizationVolunteer ov : requestedorgs){
            Organization o = ov.getOrg();            
            Object[] row = new Object[7];
            row[0] = o.getId();
            row[1] = o.getName();
            row[3] = o.getAddress();
            row[4] = o.getCity();
            row[5] = o.getNeedVolunteerCount();
            row[6] = ov.getRequeststatus();
            
            // Finding org type
            for(Enterprise e: business.getEnterprisedirectory().getAllEnter()){
                Organization orgfound = e.findOrg(o.getId());
                if(orgfound!=null){
                   row[2] = e.getType();
                }
            }
            
            dtm.addRow(row);      
        }
    }

    private void populateVolunteerDetails() {
        Volunteer v = business.getVolunteer();
        int id = v.getPersonid();
        String name = v.getName();
        int age = v.getAge();
        String gender = v.getGender();
        String address = v.getAddress();
        String city = v.getCity();
        String state = v.getState();
        String country = v.getCountry();
        String contact = v.getPhone();
        
        idtxt.setText(String.valueOf(id));
        nametxt.setText(name);
        agetxt.setText(String.valueOf(age));
        genderjComboBox.setSelectedItem(gender);
        addresstxt.setText(address);
        citytxt.setText(city);
        statetxt.setText(state);
        countrytxt.setText(country);
        contacttxt.setText(contact);
    }

}
